baseURL = 'https://pluralfusion.com/'
title = "PluralFusïon"
author = "PluralFusion"
copyright = "© 2025 PluralFusion, Inc"
timeZone = 'America/New_York'


# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "pluralfusion.github.io"
themesdir = "../.."

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
googleAnalytics = "G-QSWW0WWEJJ"
googleTag = "G-QSWW0WWEJJ"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = 'series'
  author = "authors"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
