# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "Connected Health & Safety Intelligence<br/>for critical operations and everyday living"
images = ['images/pf-infinity-diag.svg','images/pf-infinity-diag.png']
mainMenuLogo = "images/pf-infinity-diag.svg"
heroLogo = 'images/pf-infinity-diag.svg'

# For favicons
## Chrome Browser
themeColor = "#fff"

# Google Analytics
googleAnalytics = "G-QSWW0WWEJJ"
#googleTag = "G-QSWW0WWEJJ"

# Alert
alert = false
alertDismissable = true
alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

# Pre-footer
footerAbout = true
footerAboutTitle = "Few Words About Us"
footerAboutText = "We protect your website so you can provide a safe environment to build trust and improve the user experience of your visitors.<br/><br/>Salvus Site is the partner that you can rely on for preventive and reactive cybersecurity."

[options]
  bootStrapJs = true
  breadCrumb = false
  listCategoryFilter = true
  listTagFilter = true
